### ISSUE TITLE
Add Makefile to facilitate common tasks

### ISSUE THREAD

**Issue by zetxek** [ho-nl/docker-development-box#19]
Inspired by https://github.com/wodby/docker4drupal, a similar project but for Drupal, it would be nice to have a `Makefile` that facilitates some common tasks while developing.

Some of the shortcuts that the `Makefile` provides (via [the referenced file `docker.mk`](https://github.com/wodby/docker4drupal/blob/master/docker.mk)) are:

- start
- stop 
- help
- open a ssh session
- run drush commands (we could run `php bin/magento` commands and `n98-magerun2` too)

As mentioned in #17, this file could be a good place to have startup/shutdown commands, for example.

**Comment by paales** [comment]
I like the idea to help developers make things more easy and we should if we can!

If the current nfs sync works (#18) out we'd have the following 'commands' to run:
- start: `docker-compose up -d`
- stop: `docker-compose down`
- ssh: [See README](https://github.com/ho-nl/docker-development-box#how-do-i-connect-to-my-container-over-ssh-directly)
- cli: since php is running locally, everything can start locally

Do you think an additional CLI tool would make things more understandable / easier to use? I currently like the idea that is is as bare bones as possible, but I'm open to ideas.

**Comment by zetxek** [comment]
The nice thing of the `Makefile` is that it's native also. I'll make a proof of concept, with some ideas.

Something I particularly like in docker environments is using a makefile + `.env` to customize the image and runtime variables (such as URL of the project, name, mysql passwords...)

**Comment by hnsr** [comment]
Closing some old issues that don't seem relevant anymore, please re-open if you still encounter this issue.
